// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gx/grainite/protos/client_interface_v1.proto

package grpcclient

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status_Code int32

const (
	Status_OK                  Status_Code = 0
	Status_SERVICE_UNAVAILABLE Status_Code = 1
	Status_SERVICE_ERROR       Status_Code = 2
	Status_TIMEOUT             Status_Code = 3
	Status_INVALID_APP         Status_Code = 4
	Status_INVALID_TOPIC       Status_Code = 5
	Status_INVALID_TABLE       Status_Code = 6
	Status_INVALID_KEY         Status_Code = 7
	Status_INVALID_MAPID       Status_Code = 8
	Status_INVALID_MAPKEY      Status_Code = 9
	Status_INVALID_PAYLOAD     Status_Code = 10
	Status_KEY_NOT_FOUND       Status_Code = 11
	Status_MAPKEY_NOT_FOUND    Status_Code = 12
)

var Status_Code_name = map[int32]string{
	0:  "OK",
	1:  "SERVICE_UNAVAILABLE",
	2:  "SERVICE_ERROR",
	3:  "TIMEOUT",
	4:  "INVALID_APP",
	5:  "INVALID_TOPIC",
	6:  "INVALID_TABLE",
	7:  "INVALID_KEY",
	8:  "INVALID_MAPID",
	9:  "INVALID_MAPKEY",
	10: "INVALID_PAYLOAD",
	11: "KEY_NOT_FOUND",
	12: "MAPKEY_NOT_FOUND",
}

var Status_Code_value = map[string]int32{
	"OK":                  0,
	"SERVICE_UNAVAILABLE": 1,
	"SERVICE_ERROR":       2,
	"TIMEOUT":             3,
	"INVALID_APP":         4,
	"INVALID_TOPIC":       5,
	"INVALID_TABLE":       6,
	"INVALID_KEY":         7,
	"INVALID_MAPID":       8,
	"INVALID_MAPKEY":      9,
	"INVALID_PAYLOAD":     10,
	"KEY_NOT_FOUND":       11,
	"MAPKEY_NOT_FOUND":    12,
}

func (x Status_Code) String() string {
	return proto.EnumName(Status_Code_name, int32(x))
}

func (Status_Code) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d12d433719faee52, []int{0, 0}
}

type Status struct {
	Error                Status_Code `protobuf:"varint,1,opt,name=error,proto3,enum=grainite_client.Status_Code" json:"error,omitempty"`
	ErrorMessage         string      `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_d12d433719faee52, []int{0}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetError() Status_Code {
	if m != nil {
		return m.Error
	}
	return Status_OK
}

func (m *Status) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type AppendRequest struct {
	App                  string   `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	TopicName            string   `protobuf:"bytes,2,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	Events               []*Event `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	TimeoutSecs          uint32   `protobuf:"varint,4,opt,name=timeout_secs,json=timeoutSecs,proto3" json:"timeout_secs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendRequest) Reset()         { *m = AppendRequest{} }
func (m *AppendRequest) String() string { return proto.CompactTextString(m) }
func (*AppendRequest) ProtoMessage()    {}
func (*AppendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d12d433719faee52, []int{1}
}

func (m *AppendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendRequest.Unmarshal(m, b)
}
func (m *AppendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendRequest.Marshal(b, m, deterministic)
}
func (m *AppendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendRequest.Merge(m, src)
}
func (m *AppendRequest) XXX_Size() int {
	return xxx_messageInfo_AppendRequest.Size(m)
}
func (m *AppendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AppendRequest proto.InternalMessageInfo

func (m *AppendRequest) GetApp() string {
	if m != nil {
		return m.App
	}
	return ""
}

func (m *AppendRequest) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

func (m *AppendRequest) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *AppendRequest) GetTimeoutSecs() uint32 {
	if m != nil {
		return m.TimeoutSecs
	}
	return 0
}

type AppendResponse struct {
	Status               []*EventStatus `protobuf:"bytes,1,rep,name=status,proto3" json:"status,omitempty"`
	MinAppendTimestamp   uint64         `protobuf:"varint,2,opt,name=min_append_timestamp,json=minAppendTimestamp,proto3" json:"min_append_timestamp,omitempty"`
	MaxAppendTimestamp   uint64         `protobuf:"varint,3,opt,name=max_append_timestamp,json=maxAppendTimestamp,proto3" json:"max_append_timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AppendResponse) Reset()         { *m = AppendResponse{} }
func (m *AppendResponse) String() string { return proto.CompactTextString(m) }
func (*AppendResponse) ProtoMessage()    {}
func (*AppendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d12d433719faee52, []int{2}
}

func (m *AppendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendResponse.Unmarshal(m, b)
}
func (m *AppendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendResponse.Marshal(b, m, deterministic)
}
func (m *AppendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendResponse.Merge(m, src)
}
func (m *AppendResponse) XXX_Size() int {
	return xxx_messageInfo_AppendResponse.Size(m)
}
func (m *AppendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AppendResponse proto.InternalMessageInfo

func (m *AppendResponse) GetStatus() []*EventStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *AppendResponse) GetMinAppendTimestamp() uint64 {
	if m != nil {
		return m.MinAppendTimestamp
	}
	return 0
}

func (m *AppendResponse) GetMaxAppendTimestamp() uint64 {
	if m != nil {
		return m.MaxAppendTimestamp
	}
	return 0
}

type Event struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Payload              []byte   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_d12d433719faee52, []int{3}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Event) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type EventStatus struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Lsn                  []byte   `protobuf:"bytes,2,opt,name=lsn,proto3" json:"lsn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventStatus) Reset()         { *m = EventStatus{} }
func (m *EventStatus) String() string { return proto.CompactTextString(m) }
func (*EventStatus) ProtoMessage()    {}
func (*EventStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_d12d433719faee52, []int{4}
}

func (m *EventStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventStatus.Unmarshal(m, b)
}
func (m *EventStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventStatus.Marshal(b, m, deterministic)
}
func (m *EventStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventStatus.Merge(m, src)
}
func (m *EventStatus) XXX_Size() int {
	return xxx_messageInfo_EventStatus.Size(m)
}
func (m *EventStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_EventStatus.DiscardUnknown(m)
}

var xxx_messageInfo_EventStatus proto.InternalMessageInfo

func (m *EventStatus) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *EventStatus) GetLsn() []byte {
	if m != nil {
		return m.Lsn
	}
	return nil
}

func init() {
	proto.RegisterEnum("grainite_client.Status_Code", Status_Code_name, Status_Code_value)
	proto.RegisterType((*Status)(nil), "grainite_client.Status")
	proto.RegisterType((*AppendRequest)(nil), "grainite_client.AppendRequest")
	proto.RegisterType((*AppendResponse)(nil), "grainite_client.AppendResponse")
	proto.RegisterType((*Event)(nil), "grainite_client.Event")
	proto.RegisterType((*EventStatus)(nil), "grainite_client.EventStatus")
}

func init() {
	proto.RegisterFile("gx/grainite/protos/client_interface_v1.proto", fileDescriptor_d12d433719faee52)
}

var fileDescriptor_d12d433719faee52 = []byte{
	// 573 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0xed, 0x4e, 0xdb, 0x3c,
	0x14, 0x26, 0x4d, 0x09, 0xf4, 0xa4, 0x05, 0xbf, 0x06, 0xbd, 0x44, 0x13, 0xdb, 0xba, 0xec, 0x4f,
	0x7f, 0x4c, 0x29, 0x2b, 0xbb, 0x81, 0x40, 0x33, 0x14, 0x51, 0x9a, 0xc8, 0x14, 0x24, 0xa6, 0x49,
	0x96, 0x17, 0xbc, 0x2a, 0x1a, 0xf9, 0x58, 0x6c, 0x10, 0x5c, 0xc7, 0xee, 0x62, 0x57, 0xb4, 0x0b,
	0xd9, 0x05, 0x4c, 0x71, 0x12, 0x16, 0x60, 0xfc, 0x3b, 0x79, 0x3e, 0xce, 0x63, 0x9f, 0x13, 0xc3,
	0xbb, 0xe5, 0xed, 0x78, 0x59, 0xb0, 0x38, 0x8d, 0x25, 0x1f, 0xe7, 0x45, 0x26, 0x33, 0x31, 0x8e,
	0xae, 0x62, 0x9e, 0x4a, 0x1a, 0xa7, 0x92, 0x17, 0x5f, 0x59, 0xc4, 0xe9, 0xcd, 0x7b, 0x47, 0x51,
	0x78, 0xb3, 0x91, 0xd2, 0x4a, 0x63, 0xff, 0xea, 0x80, 0x71, 0x2a, 0x99, 0xbc, 0x16, 0x78, 0x02,
	0xab, 0xbc, 0x28, 0xb2, 0xc2, 0xd2, 0x86, 0xda, 0x68, 0x63, 0xb2, 0xeb, 0x3c, 0xd2, 0x3a, 0x95,
	0xce, 0x39, 0xcc, 0x2e, 0x39, 0xa9, 0xa4, 0xf8, 0x2d, 0x0c, 0x54, 0x41, 0x13, 0x2e, 0x04, 0x5b,
	0x72, 0xab, 0x33, 0xd4, 0x46, 0x3d, 0xd2, 0x57, 0xe0, 0x49, 0x85, 0xd9, 0xbf, 0x35, 0xe8, 0x96,
	0x26, 0x6c, 0x40, 0x27, 0x38, 0x46, 0x2b, 0x78, 0x07, 0xb6, 0x4e, 0x3d, 0x72, 0xee, 0x1f, 0x7a,
	0xf4, 0x6c, 0xee, 0x9e, 0xbb, 0xfe, 0xcc, 0x3d, 0x98, 0x79, 0x48, 0xc3, 0xff, 0xc1, 0xa0, 0x21,
	0x3c, 0x42, 0x02, 0x82, 0x3a, 0xd8, 0x84, 0xb5, 0x85, 0x7f, 0xe2, 0x05, 0x67, 0x0b, 0xa4, 0xe3,
	0x4d, 0x30, 0xfd, 0xf9, 0xb9, 0x3b, 0xf3, 0xa7, 0xd4, 0x0d, 0x43, 0xd4, 0x2d, 0x0d, 0x0d, 0xb0,
	0x08, 0x42, 0xff, 0x10, 0xad, 0x3e, 0x80, 0x54, 0x5b, 0xa3, 0x6d, 0x3b, 0xf6, 0x2e, 0xd0, 0x5a,
	0x5b, 0x73, 0xe2, 0x86, 0xfe, 0x14, 0xad, 0x63, 0x0c, 0x1b, 0x2d, 0xa8, 0x94, 0xf5, 0xf0, 0x16,
	0x6c, 0x36, 0x58, 0xe8, 0x5e, 0xcc, 0x02, 0x77, 0x8a, 0xa0, 0xf4, 0x1e, 0x7b, 0x17, 0x74, 0x1e,
	0x2c, 0xe8, 0xc7, 0xe0, 0x6c, 0x3e, 0x45, 0x26, 0xde, 0x06, 0x54, 0x79, 0x5a, 0x68, 0xdf, 0xfe,
	0xa1, 0xc1, 0xc0, 0xcd, 0x73, 0x9e, 0x5e, 0x12, 0xfe, 0xfd, 0x9a, 0x0b, 0x89, 0x11, 0xe8, 0x2c,
	0xcf, 0xd5, 0x7c, 0x7b, 0xa4, 0x2c, 0xf1, 0x4b, 0x00, 0x99, 0xe5, 0x71, 0x44, 0x53, 0x96, 0x34,
	0xc3, 0xeb, 0x29, 0x64, 0xce, 0x12, 0x8e, 0x1d, 0x30, 0xf8, 0x0d, 0x4f, 0xa5, 0xb0, 0xf4, 0xa1,
	0x3e, 0x32, 0x27, 0xff, 0x3f, 0xd9, 0x89, 0x57, 0xd2, 0xa4, 0x56, 0xe1, 0x37, 0xd0, 0x97, 0x71,
	0xc2, 0xb3, 0x6b, 0x49, 0x05, 0x8f, 0x84, 0xd5, 0x1d, 0x6a, 0xa3, 0x01, 0x31, 0x6b, 0xec, 0x94,
	0x47, 0xc2, 0xfe, 0xa9, 0xc1, 0x46, 0x73, 0x2a, 0x91, 0x67, 0xa9, 0xe0, 0xf8, 0x03, 0x18, 0x42,
	0xad, 0xd6, 0xd2, 0x54, 0xca, 0xee, 0xbf, 0x53, 0xaa, 0xf5, 0x93, 0x5a, 0x8b, 0xf7, 0x60, 0x3b,
	0x89, 0x53, 0xca, 0x54, 0x2f, 0x5a, 0x46, 0x08, 0xc9, 0x92, 0x5c, 0x5d, 0xa2, 0x4b, 0x70, 0x12,
	0xa7, 0x55, 0xcc, 0xa2, 0x61, 0x94, 0x83, 0xdd, 0x3e, 0x75, 0xe8, 0xb5, 0x83, 0xdd, 0x3e, 0x72,
	0xd8, 0xfb, 0xb0, 0xaa, 0xa2, 0xcb, 0xc9, 0x7d, 0xe3, 0x77, 0x6a, 0x72, 0x7d, 0x52, 0x96, 0xd8,
	0x82, 0xb5, 0x9c, 0xdd, 0x5d, 0x65, 0xec, 0x52, 0x25, 0xf6, 0x49, 0xf3, 0x69, 0x87, 0x60, 0xb6,
	0xce, 0x8b, 0xc7, 0xad, 0xdb, 0x69, 0x23, 0x73, 0xb2, 0xf3, 0xcc, 0x7f, 0x7d, 0x7f, 0x31, 0x04,
	0xfa, 0x95, 0x48, 0xeb, 0xae, 0x65, 0x39, 0xf9, 0x0c, 0xeb, 0x47, 0xb5, 0x07, 0x87, 0x60, 0xaa,
	0xfd, 0x54, 0x47, 0xc5, 0xaf, 0x9e, 0x74, 0x7b, 0xb0, 0xf2, 0x17, 0xaf, 0x9f, 0xe5, 0xab, 0xe1,
	0xdb, 0x2b, 0x07, 0x7b, 0x70, 0xff, 0x2a, 0x9d, 0x4a, 0x73, 0xd0, 0x3d, 0x2a, 0xf2, 0xe8, 0xd3,
	0xce, 0x5f, 0x38, 0x4b, 0xc6, 0xcb, 0x22, 0x8f, 0x2a, 0xfa, 0x8b, 0xa1, 0x1e, 0xf3, 0xfe, 0x9f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x42, 0xcb, 0x5d, 0x97, 0xfc, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GrainiteClient is the client API for Grainite service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GrainiteClient interface {
	TopicAppend(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*AppendResponse, error)
}

type grainiteClient struct {
	cc *grpc.ClientConn
}

func NewGrainiteClient(cc *grpc.ClientConn) GrainiteClient {
	return &grainiteClient{cc}
}

func (c *grainiteClient) TopicAppend(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*AppendResponse, error) {
	out := new(AppendResponse)
	err := c.cc.Invoke(ctx, "/grainite_client.Grainite/topicAppend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrainiteServer is the server API for Grainite service.
type GrainiteServer interface {
	TopicAppend(context.Context, *AppendRequest) (*AppendResponse, error)
}

func RegisterGrainiteServer(s *grpc.Server, srv GrainiteServer) {
	s.RegisterService(&_Grainite_serviceDesc, srv)
}

func _Grainite_TopicAppend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrainiteServer).TopicAppend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grainite_client.Grainite/TopicAppend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrainiteServer).TopicAppend(ctx, req.(*AppendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Grainite_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grainite_client.Grainite",
	HandlerType: (*GrainiteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "topicAppend",
			Handler:    _Grainite_TopicAppend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gx/grainite/protos/client_interface_v1.proto",
}
